services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.server
  #   volumes:
  #     - ./src:/src
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST:redis

